### ISSUE TITLE
Contradictory Language

### ISSUE THREAD

**Issue by vibhavp** [todogroup/opencodeofconduct#40] opened 2015-08-03 15:04 UTC
Quoting the "Definitions" clause of the CoC:

> Harassment includes, but is not limited to:
> 
> - Offensive comments related to gender, gender identity and expression, sexual orientation, disability,
> mental illness, neuro(a)typicality, physical appearance, body size, race, age, regional discrimination,
> political or religious affiliation

This somewhat contradicts the passage explicitly saying we don't accept complaints of these so called "reverse"-isms, and that we prioritize oppressed people over the privileged  

> Our open source community prioritizes marginalized people’s safety over privileged people’s comfort. We will not act on complaints regarding:
> 
> - 'Reverse' -isms, including 'reverse racism,' 'reverse sexism,' and 'cisphobia'

**Comment by MrStonedOne** [comment] 2015-08-03 17:16
>We strive to be a community that welcomes and supports people of all backgrounds and identities.

and 

>Our open source community prioritizes marginalized people’s safety over privileged people’s comfort. We will not act on complaints regarding:

>‘Reverse’ -isms, including ‘reverse racism,’ ‘reverse sexism,’ and ‘cisphobia’

Pick 1. Both statements can not coexist.

#40 also fails to use quotes and is unreadable.

**Comment by vibhavp** [comment] 2015-08-03 17:50
Why the spam? :(

**Comment by MrStonedOne** [comment] 2015-08-03 17:51
They kept closing my PRs and issue reports.

**Comment by NuckChorris** [comment] 2015-08-03 17:59
Correction: you kept reopening them instead of starting a civil conversation on the topic in #40

Anyways I think I said this elsewhere but this section got a bit of discussion towards the end of #17

**Comment by sir-pinecone** [comment] 2015-08-04 03:17
I fail to understand how allowing marginalized people to be racist and sexist will result in you creating a welcoming community free of such discourse. Sounds like this has an agenda that extends beyond creating a fair and welcoming environment for all.

**Comment by Addvilz** [comment] 2015-08-04 09:05
@sir-pinecone of course it does - why are you surprised, exactly? This might have started as a noble idea at first, and I commend for that, but I don't believe future of this project holds any promise of impartiality, nor that it has any real future at all, if it continues the path that it is on now. Mainly, because open source community isn't really interested in furthering totalitarian social justice agendas.

As for the issue, it was pointed out many times in #17, and was dismissed mainly with something similar to, I, quote
> This is a critical part of this PR and I will not be removing it.

I kind of lost all hope after this got merged, on basis that it apparently needs to be done "sooner rather than later" - apparently it's a reason enough, even if the changes are flawed and compromises the very essence of what this code should stand for.

This might, however, be addressed if #56 or #58 is somehow accepted, but I am not inclined to believe miracles today.

And I hope so much I am wrong...

**Comment by vibhavp** [comment] 2015-08-04 09:12
Discussing the CoC's nature doesn't belong here, because it's something we have already decided on keeping. You're free to fork and remove it.

I made this bug report to get these two contradictory clauses removed. We want to make sure to any potential contributor that their complaints of "reversisms" wouldn't be accepted/listened to.

**Comment by M3gaFr3ak** [comment] 2015-08-04 10:22
Question: will a request be accepted if I report a user belonging to a marginalised group for being an asshole instead of accusing them of reverse-isms? This whole paragraph seems to indicate that the words aren't liked because they are in parenthesies.

**Comment by mvirkkunen** [comment] 2015-08-04 15:27
[Note: I explicitly do not consent to the code of conduct as it is due to multiple issues]

The second paragraph by OP makes this entire thing a non-starter for anything I'm involved in. "Protecting" minorities by allowing them to discriminate against the "majorities" is a fucking idiotic idea and belongs on Tumblr and not a respectable website such as Github.

**Comment by vibhavp** [comment] 2015-08-04 15:51
@M3gaFr3ak The CoC explicitly says that we prioritize "marginalized people’s safety over privileged people’s comfort". So, its clear by what we mean by reverse-racism/sexism.

@mvirkkunen Again this was already discussed in an earlier pull request, and we have decided on keeping it. You're free to fork it and maintain your own version

**Comment by M3gaFr3ak** [comment] 2015-08-04 15:53
The problem I isn't the forking. The problem is that github is using this
coc of bigotry

**Comment by M3gaFr3ak** [comment] 2015-08-04 16:03
Might you link me to a place for this discussion?

**Comment by bkeepers** [comment] 2015-08-07 23:26
Thanks for your feedback. See https://github.com/todogroup/opencodeofconduct/issues/84.

**Closed by bkeepers** 2015-08-07 23:26 UTC
